---
# tasks file for {{ cookiecutter.role_name }}
{%- raw %}

- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family | lower }}.yml"

- name: Include OS-specific tasks
  include_tasks: "setup-{{ ansible_os_family | lower }}.yml"
{% endraw -%}
